In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report

# pd.set_option("display.max_columns", None)

# # Show all rows
# pd.set_option("display.max_rows", None)

# # Increase maximum width per cell for long text
# pd.set_option("display.max_colwidth", None)

# # Increase the overall console display width to prevent wrapping
# pd.set_option("display.width", 1000)

### Exploring the Data

In [36]:
df = pd.read_csv("./games.csv")
# df = df.sample(n=50000, random_state=42)
target = "Average playtime forever"
df.head(5)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [33]:
print("Shape of the data:")
print(df.shape)
print()
print("Number of Missing Values in Each Column:")
print(df.isna().sum())
print()
print("Info About Each Column:")
print(df.info())
print()
print(df["Release date"].value_counts())

Shape of the data:
(130100, 40)

Number of Missing Values in Each Column:
AppID                              0
Name                               1
Release date                       0
Estimated owners                   0
Peak CCU                           0
Required age                       0
Price                              0
Discount                           0
DLC count                          0
About the game                  8757
Supported languages                0
Full audio languages               0
Reviews                       117543
Header image                      84
Website                        77936
Support url                    72964
Support email                  23404
Windows                            0
Mac                                0
Linux                              0
Metacritic score                   0
Metacritic url                125718
User score                         0
Positive                           0
Negative                           0
Score rank                    130057
Achievements                       0
Recommendations                    0
Notes                         106003
Average playtime forever           0
Average playtime two weeks         0
Median playtime forever            0
Median playtime two weeks          0
Developers                      8740
Publishers                      9233
Categories                      9274
Genres                          8710
Tags                           44000
Screenshots                     6235
Movies                        130100
dtype: int64

Info About Each Column:
<class 'pandas.DataFrame'>
RangeIndex: 130100 entries, 0 to 130099
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       130100 non-null  int64
 1   Name                        130099 non-null  str
 2   Release date                130100 non-null  str
 3   Estimated owners            130100 non-null  str
 4   Peak CCU                    130100 non-null  int64
 5   Required age                130100 non-null  int64
 6   Price                       130100 non-null  float64
 7   Discount                    130100 non-null  int64
 8   DLC count                   130100 non-null  int64
 9   About the game              121343 non-null  str
 10  Supported languages         130100 non-null  str
 11  Full audio languages        130100 non-null  str
 12  Reviews                     12557 non-null   str
 13  Header image                130016 non-null  str
 14  Website                     52164 non-null   str
 15  Support url                 57136 non-null   str
 16  Support email               106696 non-null  str
 17  Windows                     130100 non-null  bool
 18  Mac                         130100 non-null  bool
 19  Linux                       130100 non-null  bool
 20  Metacritic score            130100 non-null  int64
 21  Metacritic url              4382 non-null    str
 22  User score                  130100 non-null  int64
 23  Positive                    130100 non-null  int64
 24  Negative                    130100 non-null  int64
 25  Score rank                  43 non-null      float64
 26  Achievements                130100 non-null  int64
 27  Recommendations             130100 non-null  int64
 28  Notes                       24097 non-null   str
 29  Average playtime forever    130100 non-null  int64
 30  Average playtime two weeks  130100 non-null  int64
 31  Median playtime forever     130100 non-null  int64
 32  Median playtime two weeks   130100 non-null  int64
 33  Developers                  121360 non-null  str
 34  Publishers                  120867 non-null  str
 35  Categories                  120826 non-null  str
 36  Genres                      121390 non-null  str
 37  Tags                        86100 non-null   str
 38  Screenshots                 123865 non-null  str
 39  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(15), str(19)
memory usage: 37.1 MB
None

Release date
Oct 23, 2025    193
Jun 19, 2025    176
Oct 24, 2025    173
Oct 31, 2025    157
Oct 22, 2025    155
               ...
Sep 5, 2011       1
May 15, 2016      1
Sep 8, 2026       1
Mar 31, 2026      1
Jun 30, 2026      1
Name: count, Length: 5141, dtype: int64

In [34]:
print(df[target].value_counts())

for item in df[target]:
    print(item)

Average playtime forever
0       103087
1          315
2          154
3          151
9          137
         ...
1334         1
1123         1
8630         1
5222         1
3864         1
Name: count, Length: 3037, dtype: int64
0
8
0
0
0
0
675
0
0
0
0
0
489
0
0
0
0
203
0
88
0
480
0
0
0
0
342
111
0
0
0
0
0
0
88
0
0
0
0
0
0
220
183
0
0
0
0
0
0
0
0
0
0
0
205
0
0
0
0
0
0
0
0
0
0
320
0
0
0
217
0
0
0
0
166
0
0
0
0
0
0
91
0
0
335
470
0
0
0
0
0
0
0
0
37
263
0
0
0
17
383
0
0
1977
0
127
0
0
0
0
0
0
0
0
0
0
0
57
0
0
0
0
0
0
0
185
0
0
0
0
0
0
0
0
167
0
0
0
0
0
0
0
0
265
0
0
0
0
0
0
145
0
0
0
391
0
0
0
99
0
0
0
503
0
0
0
0
0
0
0
0
0
1421
0
0
0
0
0
0
0
280
526
337
0
0
362
0
156
0
0
0
0
0
0
0
0
0
0
0
103
0
537
0
0
0
0
0
7
0
0
0
0
0
0
235
0
111
205
0
0
0
108
0
0
0
0
0
0
0
41
421
24
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3605
0
0
0
0
0
0
0
0
0
0
925
0
3258
0
0
0
0
0
0
0
0
0
0
172
1493
0
0
149
0
226
0
0
0
83
0
0
0
0
0
20
0
0
0
0
0
0
135
0
0
0
0
0
0
0
0
0
38
0
0
0
0
0
309
168
0
0
0
0
0
0
0
0
0
0
0
0
0
641
0
0
0
0
0
818
0
0
0
0
1421
0
884
0
0
0
1643
0
0
0
0
0
0
349
0
549
0
0
0
445
392
0
247
0
0
0
0
0
0
0
290
0
0
0
0
0
139
0
74
0
0
0
56
0
0
0
234
0
9
0
0
0
0
0
0
0
176
0
0
0
0
493
0
0
0
396
0
0
0
1
0
0
0
0
155
0
10
153
0
0
0
0
0
0
475
562
0
0
0
0
188
0
0
656
0
0
0
0
0
0
0
0
0
0
117
0
0
0
0
0
0
0
15
84
0
0
0
0
0
0
0
2259
0
0
0
62
0
0
0
0
0
0
0
0
0
0
0
0
0
0
135
17
0
0
0
0
0
0
0
574
0
0
0
293
0
0
0
0
0
0
0
0
0
710
236
229
217
0
0
544
678
0
0
0
0
0
0
0
0
0
0
0
0
0
1051
0
40
0
0
73
0
0
0
0
0
0
0
0
268
0
0
0
91
0
0
0
0
0
0
57
0
0
0
0
0
0
0
569
0
239
0
0
0
0
0
0
0
0
0
0
278
0
271
0
0
0
67
169
284
0
0
0
0
0
0
3758
0
152
0
0
441
0
0
0
0
0
0
0
0
0
0
55
0
0
1370
0
0
0
0
73
0
0
0
173
0
0
0
328
0
0
0
0
0
0
0
0
229
0
757
733
0
0
0
0
0
51
0
0
214
0
0
0
0
0
0
0
0
0
0
0
0
0
0
488
0
186
257
0
0
0
0
0
0
487
0
0
0
0
0
0
0
0
0
1024
0
0
0
0
0
0
0
0
360
0
0
0
290
0
419
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
34
0
278
0
294
0
0
375
0
0
0
0
0
0
0
0
0
0
214
0
0
0
0
0
210
0
445
0
0
0
1779
0
0
154
0
0
0
0
0
28
0
0
0
0
0
1413
0
0
0
0
0
202
172
0
110
271
0
0
104
0
0
285
0
0
0
0
0
0
0
0
292
0
0
369
0
0
1108
0
0
0
38
0
0
0
0
0
0
0
0
0
0
0
0
245
0
0
0
0
0
320
0
205
0
0
0
0
0
0
0
0
0
0
0
0
0
244
0
0
0
0
0
0
1290
263
49
0
861
0
31
0
17
0
0
0
0
63
0
0
0
0
0
1015
46
0
0
0
0
43
0
0
0
270
726
0
0
11
0
0
0
0
0
532
0
225
0
0
0
0
0
0
0
129
0
0
0
0
0
0
0
14
0
0
557
0
0
0
220
0
0
0
0
0
0
0
153
279
0
37
0
0
0
0
252
194
261
0
0
0
399
0
0
0
171
0
0
0
0
0
0
0
0
7
0
10
0
0
0
0
0
354
0
0
128
0
80
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
147
0
0
0
0
0
0
0
0
624
566
228
68
0
0
0
0
0
0
0
0
0
0
882
158
0
0
0
0
162
0
0
1
0
0
0
0
0
0
0
0
0
806
0
0
289
0
0
0
0
0
0
0
1492
0
0
0
0
0
0
0
0
0
0
0
0
478
0
0
0
0
0
0
0
106
0
96
0
0
0
0
0
140
252
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
451
631
0
0
0
0
0
0
661
0
0
0
0
412
0
0
758
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
105
0
0
0
0
0
0
0
0
0
0
0
0
32
10
0
307
0
0
0
0
6579
0
0
0
0
0
0
0
0
0
234
0
0
0
0
0
0
0
2265
0
0
0
625
0
0
0
0
121
0
0
0
0
0
168
0
0
0
273
0
0
0
0
0
70
0
0
106
0
0
0
0
0
0
1647
0
135
0
0
0
0
0
92
0
0
0
26
0
0
0
197
0
0
0
326
2347
0
243
74
958
0
7134
0
0
545
0
0
298
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
142
0
299
346
0
0
0
0
1539
0
0
0
49
0
0
0
420
0
1268
0
0
260
0
0
1
0
0
0
0
36
0
542
0
0
0
273
0
0
0
0
0
95
0
0
0
0
0
0
0
51
0
0
189
0
0
0
457
0
0
0
0
0
0
0
0
158
0
67
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
5
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
40
0
146
0
0
0
0
0
0
0
0
0
0
281
0
78
30
0
0
0
0
0
0
0
0
0
81
0
0
0
254
0
0
0
0
160
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
313
0
0
358
0
0
0
0
0
0
0
0
0
0
41
183
0
0
0
189
0
128
0
0
0
0
0
0
0
0
0
0
0
0
0
0
83
0
0
0
0
0
274
4590
445
0
0
339
0
42
0
15
0
0
0
0
0
0
621
0
4193
26
323
0
0
0
128
3
224
0
249
0
0
229
0
0
0
131
0
0
58
0
0
0
40
0
0
0
0
0
0
0
0
0
0
0
231
0
0
0
0
0
0
0
0
1383
0
0
0
0
0
15
0
0
0
2050
123
0
268
0
0
0
0
0
0
0
101
0
0
0
0
0
0
56
376
0
246
0
37
0
0
0
0
0
0
200
0
0
0
88
0
0
0
0
0
0
0
0
0
58
0
0
0
382
227
0
0
124
0
0
0
419
0
0
453
0
0
0
0
0
0
0
602
0
0
4
373
0
0
0
0
0
1
0
0
0
0
681
0
19829
0
2593
0
0
0
168
0
1028
0
0
0
109
0
0
0
225
0
0
0
0
0
0
0
0
0
0
891
0
1270
0
102
0
0
0
0
0
0
158
0
0
1685
0
0
0
0
0
270
50
0
0
0
0
0
313
0
0
363
0
0
2
0
0
359
0
0
0
0
0
449
0
0
0
0
0
0
0
50
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
301
0
193
135
1719
0
226
0
0
0
0
0
0
0
6826
0
0
0
0
0
0
0
0
0
0
0
0
0
0
102
0
0
0
0
118
0
0
0
293
8
0
0
0
0
0
0
0
0
0
250
74
0
0
249
0
0
288
0
0
0
0
348
0
0
0
0
0
157
0
0
0
0
0
385
0
0
321
0
0
133
0
0
0
0
0
0
0
0
234
1661
0
0
0
0
0
0
0
0
0
0
0
0
0
0
341
0
0
170
0
0
0
154
0
0
3351
0
0
0
0
0
0
0
235
0
0
0
0
0
0
0
0
0
628
0
0
58
0
0
0
0
0
0
0
0
0
0
1177
0
0
0
0
0
0
280
0
0
65
73
44
0
0
0
0
0
0
0
0
0
405
0
90
0
222
2294
0
0
1863
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2651
0
231
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
271
0
0
0
0
0
0
123
0
0
0
0
226
0
0
0
128
0
0
0
0
0
0
1
0
0
0
0
319
0
211
0
509
0
0
0
256
0
0
0
0
0
28
64
396
82
0
0
0
0
0
0
0
0
0
0
0
128
0
0
0
0
0
218
204
21
0
664
0
0
85
0
0
256
0
0
0
0
0
0
0
0
0
0
264
628
0
0
0
0
12927
0
0
0
0
0
0
475
0
0
147
0
0
0
0
0
0
0
55
0
0
0
303
0
0
0
0
0
534
0
0
0
850
0
0
0
0
0
266
196
0
259
0
1530
0
0
0
0
0
153
0
192
133
0
966
0
0
0
0
0
0
1321
0
0
0
0
0
140
0
0
0
133
0
0
0
0
0
0
0
0
15
22
0
2580
0
33
0
2493
0
0
0
0
0
0
0
0
0
0
0
0
0
0
332
0
0
377
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
113
0
0
0
0
0
0
0
0
0
0
141
0
124
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
204
0
1
0
0
147
0
0
0
0
0
0
0
0
0
0
0
523
0
0
2
0
0
0
0
0
0
0
0
0
0
207
163
3223
0
0
92
0
0
0
0
0
0
30
0
0
0
0
0
0
0
0
0
0
0
0
0
145
0
0
0
0
0
0
0
0
0
115
399
0
340
377
0
0
5
0
0
0
0
0
473
0
0
0
0
3
0
0
0
0
26
0
0
0
0
0
0
0
0
0
62
0
0
0
0
0
64
0
0
0
0
0
0
0
174
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
22
0
0
0
770
2244
0
121
815
0
0
0
0
0
0
0
389
0
0
0
10
1852
0
0
0
0
296
0
0
0
0
0
0
0
0
377
0
0
0
0
0
85
0
0
0
0
0
0
0
0
0
0
0
0
54
0
0
0
0
0
461
223
0
0
0
0
0
0
0
0
0
0
0
0
0
52
0
0
0
0
316
0
0
0
2623
0
0
0
142
0
0
0
927
0
0
143
0
0
0
0
225
0
0
16
0
0
0
0
0
115
98
0
0
0
0
0
38
0
0
0
0
199
0
0
0
0
0
0
0
0
0
0
79
0
0
5857
0
0
0
0
141
0
210
0
0
0
0
0
0
0
0
0
0
261
0
0
416
0
0
0
0
0
0
1437
0
0
0
0
0
0
68
0
0
0
0
0
0
0
123
0
249
0
0
0
0
552
0
322
0
0
0
0
0
0
0
100
0
98
0
262
414
0
0
0
0
0
472
0
0
0
0
1104
258
0
0
0
0
30
0
0
0
0
0
0
0
1091
0
0
0
1281
0
0
0
587
0
0
0
0
0
49
0
0
0
0
188
0
0
1063
0
0
0
45
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
968
0
233
0
0
0
303
0
0
140
0
0
0
0
0
0
99
0
0
0
0
0
0
0
147
0
0
0
0
0
325
0
55
0
136
0
0
0
0
0
0
0
0
0
0
86
334
0
0
0
315
0
296
0
0
601
0
18
0
0
340
0
919
0
0
0
584
0
0
0
0
0
0
0
0
0
0
0
0
0
36
0
0
0
0
0
192
0
110
286
0
0
0
0
0
0
1409
0
0
0
0
0
0
0
0
57
0
0
0
0
0
0
404
0
0
0
0
0
54
0
0
0
0
0
0
0
0
0
0
0
0
17
0
0
0
0
0
0
0
0
0
0
0
0
0
32
0
0
0
0
114
36
0
0
0
0
0
0
0
0
0
0
0
0
0
277
0
99
0
8
0
0
0
0
0
108
0
0
0
11834
0
0
0
739
0
268
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1484
3701
0
0
0
0
0
0
0
0
0
0
0
0
457
0
0
0
0
0
951
0
0
0
179
0
495
0
0
0
0
0
0
0
201
1246
0
0
0
0
0
12
0
0
0
0
0
0
0
0
257
0
0
658
0
0
0
0
0
0
115
0
130
0
0
36
0
0
0
0
0
0
0
3
0
2175
392
0
0
0
0
280
0
0
89
87
104
0
5
0
0
0
0
179
0
526
0
2387
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
12
0
174
9
0
289
0
0
0
0
0
147
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
810
0
0
0
0
0
117
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1386
0
0
0
0
0
0
0
0
0
0
0
0
0
0
191
420
0
0
0
90
0
0
0
0
41
0
0
0
0
0
0
194
0
0
0
0
0
0
0
0
0
257
0
0
0
128
0
0
0
0
0
0
358
0
139
0
0
0
0
0
113
0
0
202
0
0
0
0
0
0
0
3393
245
230
0
0
0
0
0
0
0
0
0
15
17
0
0
32
0
0
0
0
0
100
0
71
54
0
632
0
0
0
36
0
0
0
0
2
0
0
0
0
16
0
0
0
0
0
0
0
114
0
0
0
0
0
0
279
0
447
0
45
0
315
0
0
0
0
0
0
0
0
407
0
148
501
0
0
0
0
0
0
0
0
0
0
1103
205
68
249
0
0
87
0
0
0
0
0
146
0
0
60
0
0
0
0
0
3
0
0
23
0
45
0
0
39
0
0
0
0
0
0
0
228
0
0
282
0
0
0
0
0
0
0
0
0
251
0
208
0
0
0
412
231
407
0
0
0
0
0
148
0
10
0
0
0
218
0
0
0
0
303
0
0
0
0
0
0
453
0
0
0
255
0
234
14
91
0
89
0
0
0
0
0
0
0
0
0
0
0
0
0
352
0
0
0
113
613
0
0
245
0
0
0
0
0
0
0
0
0
7
0
0
0
0
0
0
0
84
0
0
0
147
0
4161
0
0
0
0
0
0
0
0
0
312
1
0
0
0
293
0
0
0
0
1105
0
0
0
0
0
0
5930
0
809
0
0
578
3516
0
0
119
0
0
0
0
0
0
0
0
0
0
17
0
19
0
0
0
213
0
0
0
0
0
0
0
0
0
0
1368
183
0
0
0
215
0
0
82
0
0
0
13
0
0
0
0
0
0
0
266
611
0
0
163
0
0
0
0
0
436
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
278
0
72
0
0
0
0
0
988
0
0
0
0
0
0
0
0
176
2625
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
199
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
245
124
0
0
0
0
0
21
0
0
0
0
0
0
0
0
0
0
0
196
0
112
0
0
0
0
0
0
0
0
0
0
40
0
0
0
0
0
0
0
499
659
0
0
0
0
0
0
0
0
72
0
0
0
229
0
0
0
0
651
450
0
121
0
193
0
0
0
4
0
1380
0
145
0
0
0
0
428
0
0
0
0
397
0
0
288
0
0
0
0
0
0
0
1676
160
52
304
0
0
0
220
900
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
181
25
298
0
0
0
0
0
0
0
0
0
290
0
0
0
0
170
0
0
0
943
0
0
0
0
0
0
0
0
0
188
0
0
191
0
0
21
0
0
0
0
0
0
0
0
0
0
233
0
0
0
6673
2378
0
0
0
201
136
0
354
147
0
48
0
138
200
0
245
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3
0
0
0
0
0
0
0
0
0
0
0
15
0
922
0
0
0
0
0
0
0
623
0
0
0
0
0
158
0
0
0
0
0
0
0
0
0
341
0
0
0
0
0
0
225
0
0
0
0
0
1331
0
0
0
15
0
0
0
0
0
0
0
0
32
0
0
0
0
541
592
0
0
0
0
0
1525
0
0
11
0
0
0
0
0
0
0
0
7427
196
0
0
0
263
0
0
0
0
0
0
0
0
0
0
0
0
0
0
345
183
0
0
16
0
95
0
47
317
0
0
0
0
0
0
0
48
0
0
0
0
0
0
183
0
0
0
98
0
0
0
220
71
0
0
0
0
0
243
0
0
0
0
0
0
116
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
16
0
0
0
0
0
0
354
0
132
0
0
453
37
0
1699
814
0
119
0
0
48
0
22
0
0
0
43
0
65
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
11116
0
0
136
255
0
0
0
0
43
0
0
0
0
0
0
0
145
0
0
0
0
121
0
0
0
176
0
0
0
0
0
0
0
0
0
0
0
6
202
0
0
0
0
0
38
0
0
0
0
0
0
0
0
0
0
0
52
504
0
0
54
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
214
364
0
0
0
0
0
0
0
0
0
0
0
0
246
0
0
0
336
0
0
0
0
545
0
0
0
192
0
0
0
0
0
250
422
223
27
0
0
0
0
0
0
0
0
927
0
0
0
0
0
0
0
319
0
166
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
7
107
0
9
152
0
148
0
0
0
0
0
0
0
0
7
0
0
0
0
0
0
0
0
0
0
0
0
0
146
0
0
0
35
1499
0
532
0
0
0
0
1178
41
0
0
0
0
0
8052
224
0
1835
0
0
163
0
0
0
0
2136
15
0
0
65
0
0
0
0
0
0
0
130
0
0
0
0
0
0
0
1196
34
195
0
0
0
0
0
0
237
0
0
73
946
0
332
0
42
0
0
0
0
272
38
0
0
0
0
0
0
0
0
0
0
4232
0
0
0
0
0
0
0
789
0
179
0
0
8384
0
11989
431
0
0
629
0
234
0
1512
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3
0
0
0
357
0
106
0
0
0
0
0
0
0
0
0
166
0
0
0
0
0
37
0
0
262
0
0
0
918
275
0
13
52
0
0
0
0
0
0
0
0
114
2941
0
0
0
0
0
411
0
0
0
0
0
0
0
54064
0
0
0
0
6
0
0
311
0
71
144
142
0
0
0
302
0
1
0
2
0
79
0
0
0
0
0
0
0
0
0
0
0
0
1626
43
0
0
0
185
111
0
0
0
5954
345
0
0
0
133
0
0
203
0
0
0
471
52
0
0
0
0
0
0
0
18
223
0
0
230
0
0
0
0
0
0
0
297
100
0
0
0
0
75
0
0
103
0
90
0
0
0
145
0
0
0
0
0
0
0
0
0
0
0
74
238
0
32
0
0
0
0
0
0
0
0
0
708
0
0
0
0
702
0
0
0
0
0
0
0
0
1337
502
0
0
0
0
0
1078
0
0
0
0
0
453
0
0
294
0
0
0
0
0
0
0
0
0
0
0
10
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1993
17
0
61
0
0
265
0
0
0
0
47
53
85
0
0
0
0
0
174
0
0
2
0
0
278
0
252
0
0
0
1020
5
0
0
10
0
0
0
0
0
0
0
0
0
0
0
0
0
0
614
0
0
9
84
0
0
0
0
0
332
0
0
0
0
37
0
109
1158
655
0
0
0
0
258
0
0
0
0
0
0
0
44
171
0
0
0
0
0
0
0
0
352
0
0
323
0
0
0
0
0
0
0
0
0
0
0
0
0
0
10
0
0
0
0
0
0
101
0
0
12
0
0
0
0
0
0
196
241
0
0
356
0
0
50
178
0
0
368
0
0
247
0
0
6
31
0
199
0
0
0
0
0
0
0
0
0
0
0
0
0
308
2066
28
0
0
0
144
623
27
0
0
0
0
0
991
0
0
0
0
0
0
10
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
402
0
0
0
0
0
63
0
0
0
0
133
299
104
2780
47
272
0
0
0
0
0
0
356
95
0
0
0
0
185
0
0
0
0
0
30
0
0
0
199
0
231
276
221
0
0
191
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2889
0
0
0
1392
976
0
0
2072
0
0
0
0
0
32
0
0
101
0
0
173
0
0
1808
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
506
0
505
0
0
0
0
0
0
0
367
0
0
0
0
0
0
35
0
0
0
0
300
0
0
401
0
141
0
469
0
0
0
1522
0
0
0
0
1013
0
0
0
0
0
0
259
589
0
0
0
0
102
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1327
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
119
0
0
0
0
0
0
0
0
0
0
0
230
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
19
0
0
3299
0
0
0
0
3
0
73
0
2471
0
0
0
0
0
0
0
0
0
305
186
0
0
76
0
0
0
283
0
0
0
933
0
0
0
0
0
3
0
0
0
0
0
0
0
0
0
370
0
0
0
0
0
0
2153
0
0
0
0
0
0
0
0
0
0
0
236
0
3
98
27
0
33
0
0
0
0
0
0
0
351
0
0
0
0
0
278
1028
0
0
0
9449
1043
0
2796
10
62
0
176
0
0
0
0
1255
0
0
0
0
0
110
0
0
13
0
406
0
0
0
0
0
0
0
105
0
0
0
0
0
0
0
0
0
0
0
0
162
0
0
0
0
0
0
0
0
0
136
191
0
0
454
0
0
0
0
0
0
1022
282
14
164
11
0
63
0
0
0
183
0
0
0
0
0
0
0
165
0
0
0
0
0
0
106
0
0
0
202
194
0
0
0
0
472
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
252
0
0
710
668
16
0
686
0
184
0
0
0
0
0
0
0
0
0
0
41
0
0
0
0
0
0
0
0
89
880
86
0
0
0
0
364
0
0
2437
0
0
0
0
0
0
0
0
0
942
0
0
0
0
0
391
0
0
0
191
0
50
0
0
0
229
0
275
0
368
0
0
0
0
0
0
155
0
0
60
0
0
0
498
0
0
0
0
17
0
0
0
0
0
0
6562
0
49
78
0
0
0
0
0
982
0
0
0
0
6449
0
652
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
207
0
0
0
0
0
0
176
0
0
0
0
0
0
146
0
1018
0
0
0
0
0
0
89
0
0
0
0
0
453
0
36
0
0
0
0
93
0
0
94
0
0
0
0
0
0
104
122
0
0
376
0
244
0
0
0
0
0
0
0
0
3069
0
0
0
0
297
232
0
0
117
1557
0
247
0
0
126
0
0
0
0
227
0
0
0
143
16
0
0
0
0
0
0
0
32
0
0
0
0
0
2535
0
0
0
0
31
71
0
0
0
112
0
0
0
0
0
0
0
0
1353
0
0
32
0
0
0
0
0
0
0
0
0
0
0
186
0
0
0
0
0
0
76
0
0
990
38
267
0
0
37
0
0
0
41
0
0
0
0
0
0
0
236
0
0
258
0
0
0
0
0
0
0
212
146
0
0
0
325
0
16
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
52
0
0
93
0
0
0
222
0
0
110
0
0
0
0
0
0
0
0
0
0
0
3
0
232
97
0
0
0
0
0
0
24264
0
176
0
0
0
0
0
95
0
0
86
0
1136
401
15
0
0
0
0
0
0
0
258
55
0
0
0
0
0
0
0
321
0
0
0
0
0
0
0
0
0
0
0
523
0
606
0
0
0
0
0
0
0
0
0
0
1197
0
0
0
0
0
0
0
211
83
0
0
0
0
0
0
0
0
0
336
11
0
0
219
0
0
0
254
0
0
0
0
267
162
0
300
526
0
0
1234
0
0
0
0
0
0
0
0
0
0
0
0
0
2903
0
0
0
26
0
486
0
0
0
215
0
0
0
0
0
0
0
0
0
167
0
0
0
0
34
0
0
137
0
0
609
0
0
0
0
0
268
311
0
48
0
709
0
0
256
1889
186
0
333
0
0
0
0
0
0
0
0
211
0
0
0
0
0
0
0
0
10
0
0
0
0
64
0
0
330
537
0
0
0
0
296
227
0
0
0
0
0
83
0
0
226
0
53
121
308
0
535
0
0
1387
0
0
0
159
0
0
250
0
0
264
0
0
0
0
0
40
0
0
205
0
0
0
172
0
0
0
746
0
0
0
369
0
0
0
1
0
0
47
0
0
0
651
0
0
0
0
0
0
206
0
0
0
0
604
2208
0
0
48
0
0
0
0
13
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
32
0
0
0
0
0
58
0
0
0
0
0
68
267
0
0
273
0
0
0
2251
0
0
0
0
0
0
0
0
0
0
0
0
0
0
225
0
0
0
792
0
205
0
0
0
0
0
245
0
36
0
0
0
0
0
0
0
0
0
0
0
464
0
0
0
0
0
0
93
912
665
0
0
0
13
0
0
0
16
0
27
450
0
0
0
0
0
868
0
0
0
77
0
356
0
0
111
0
7
0
0
604
0
750
0
0
0
0
14
0
0
0
0
0
267
265
0
238
251
0
0
0
0
0
0
27
32
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1653
0
0
0
91
0
0
0
0
0
0
0
0
0
0
0
0
189
0
0
0
0
0
0
0
0
0
83
0
5971
880
0
0
0
1390
11211
543
117
14
0
0
83
0
0
0
0
0
215
0
1155
0
176
0
0
0
0
0
0
89
183
0
179
118
0
3
0
0
0
0
0
19
0
0
0
0
0
0
0
0
469
99
0
0
0
0
0
1704
0
0
0
0
0
53
1103
590
0
0
0
0
3
346
0
882
0
0
0
0
0
0
0
0
0
2932
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
358
0
0
13
0
0
0
0
226
0
0
0
0
0
0
0
0
0
0
0
0
0
532
0
358
0
207
0
0
0
552
0
0
0
1634
0
0
0
0
0
0
0
0
33
134
0
0
0
0
0
0
302
0
0
0
0
86
0
0
0
0
0
0
0
0
0
0
4516
0
0
0
0
36
0
0
423
0
0
0
0
0
55
0
0
0
0
0
191
0
0
0
0
0
637
0
0
0
0
0
0
371
0
0
0
0
471
0
0
0
0
0
283
0
0
0
0
0
140
45
0
0
0
0
0
0
268
0
0
0
0
0
0
0
0
0
0
0
0
0
7
0
0
0
152
0
0
0
218
0
0
88
237
114
406
0
0
0
0
39
0
0
0
14
0
0
0
0
40
0
0
0
0
0
511
0
1796
0
480
0
356
297
171
34
0
160
2
248
0
0
0
0
189
0
316
0
0
2683
299
0
0
0
0
0
0
0
0
1611
0
345
17
0
510
139
0
0
0
0
0
0
322
0
0
0
0
0
0
0
0
0
0
0
0
0
8185
0
0
209
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
140
0
394
0
0
525
0
0
0
0
0
0
0
279
0
0
0
0
0
0
1679
596
326
0
790
0
0
0
0
0
0
5
0
0
1852
0
1
1342
0
0
19
0
0
0
0
0
0
0
194
0
0
47
0
33
289
0
0
353
0
0
225
0
95
0
435
0
27
0
0
15
0
0
0
91
0
482
0
488
0
0
0
0
0
0
0
0
0
0
0
0
0
0
472
0
0
0
0
0
0
0
0
0
0
32
0
0
0
0
326
0
0
0
0
0
0
0
0
0
0
444
0
0
0
0
0
0
0
0
1
0
0
30
0
0
0
0
0
0
0
0
0
744
49
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
23
0
0
0
0
0
0
0
0
69
0
160
0
0
0
0
0
0
0
0
0
1429
383
500
0
98
0
0
0
0
0
19
0
0
0
0
30
0
13
131
0
4081
0
0
0
0
0
0
391
0
0
0
0
0
0
0
22
1
0
0
246
0
0
15
0
0
0
0
0
0
0
0
0
644
0
0
0
601
0
149
0
0
0
119
2844
25
0
0
0
0
428
0
0
0
0
204
294
20
1331
1170
0
0
0
0
0
33
0
0
0
0
0
0
0
0
0
28
471
0
0
0
0
0
40
0
0
1
0
0
0
0
0
0
0
0
0
6
0
178
0
0
0
0
0
649
0
0
202
0
0
0
84
314
0
0
0
0
0
0
0
0
0
0
0
0
0
1236
2455
0
0
0
0
205
0
0
26
0
0
0
146
0
147
166
0
0
0
0
0
0
0
219
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
827
1416
0
0
0
0
0
0
355
0
54
0
0
0
319
312
0
0
0
728
0
0
590
0
630
0
0
0
0
0
0
0
341
0
1
0
0
231
188
0
0
5688
0
0
0
3
0
0
1806
0
0
0
0
0
0
722
0
0
273
0
0
0
0
0
0
0
8
0
729
116
0
0
209
260
0
0
0
813
5
0
0
0
0
0
0
0
0
0
0
0
22
0
0
0
0
0
0
0
0
0
0
574
0
0
0
842
0
0
0
0
0
0
173
0
0
0
0
0
0
179
0
0
0
0
0
0
0
807
1055
230
115
0
0
0
0
0
0
0
21
0
0
0
0
0
0
0
0
0
214
75
0
0
0
0
0
205
0
0
0
6
0
0
0
0
0
0
2332
0
0
0
252
12
40
0
0
0
0
0
60
977
0
0
0
0
0
0
0
0
99
0
0
0
1277
0
0
638
0
0
0
0
0
0
0
0
0
0
0
0
0
0
153
0
0
0
77
0
0
0
0
1548
0
303
0
0
0
0
0
0
0
0
0
0
0
144
526
0
0
435
0
0
261
0
0
313
0
0
0
9
0
0
0
400
0
0
0
0
397
0
0
197
0
0
0
0
0
0
0
0
80
45
0
0
273
110
0
0
0
373
0
0
25
388
0
0
0
0
0
0
0
0
0
0
0
447
5905
235
0
0
0
89
0
0
297
713
0
2099
0
0
0
0
1392
2511
0
1094
0
0
0
0
0
0
0
0
0
0
0
0
0
1910
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
509
969
0
0
0
0
0
111
0
192
174
0
0
0
0
29
358
93
0
15
158
24
0
0
272
0
0
0
0
0
103
1067
0
0
0
0
0
0
0
0
0
0
0
66
37
0
16
0
0
140
0
0
0
0
0
0
0
0
736
29
0
118
0
0
0
0
0
42
108
0
168
215
0
0
60
0
0
0
186
0
0
0
0
346
0
0
0
0
232
14
0
0
0
235
0
0
0
0
0
0
0
0
93
0
0
0
0
0
0
0
0
0
0
0
0
0
35
84
0
43
0
0
411
0
0
0
0
258
0
0
0
0
0
0
0
767
0
0
0
0
7
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
255
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
60
28
0
0
0
0
1063
0
0
652
0
0
0
0
0
0
0
3
0
0
0
0
231
989
0
0
0
0
0
0
281
432
0
0
0
0
0
71
275
329
0
0
0
0
0
0
0
0
0
0
0
1817
0
0
0
0
288
0
0
21
30
0
0
0
0
83
0
177
0
0
0
0
0
1248
0
0
0
0
22
0
0
0
0
0
0
0
0
208
0
0
0
0
0
208
0
245
0
0
0
0
1789
0
326
0
0
0
0
202
0
328
0
0
0
0
0
0
0
0
0
251
0
0
0
0
0
0
0
0
0
0
0
0
38
0
0
0
0
0
0
0
142
0
0
0
0
315
0
353
0
332
113
0
163
24
0
0
58
0
182
0
0
0
565
0
0
0
0
0
254
161
0
140
0
0
0
164
343
0
29
257
40
0
122
0
0
100
0
1164
0
0
0
117
0
0
0
243
0
0
0
0
0
0
0
0
0
0
5
0
0
0
0
0
0
0
494
0
0
0
0
642
0
0
0
0
0
0
183
0
1517
0
0
0
0
0
122
0
0
0
41
258
0
0
0
0
225
0
193
0
2138
0
0
93
0
66
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3937
415
0
0
0
0
0
0
0
0
0
0
442
0
0
249
127
0
0
0
149
893
0
0
0
1255
0
0
0
1
15
0
0
0
0
0
0
0
0
0
0
0
0
109
0
263
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
162
0
0
264
0
0
0
4413
513
0
0
0
0
438
229
0
0
0
0
0
0
0
0
156
0
438
0
87
0
0
534
257
304
0
0
0
0
15
0
0
79
0
0
0
0
0
0
0
42
0
176
1108
0
0
0
0
79
0
0
4
0
0
0
0
0
0
0
976
203
0
0
1058
753
0
0
0
0
0
0
0
0
0
0
0
0
20
0
0
0
218
0
0
14
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1816
0
0
165
0
4
0
0
0
0
0
0
0
1043
0
277
0
0
21
0
0
0
0
0
0
0
176
0
300
0
1304
0
0
0
0
0
0
46
0
47
0
0
0
0
0
0
0
119
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
226
0
0
173
0
836
50
0
0
207
0
0
122
265
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
29
0
0
0
236
0
0
0
0
0
0
0
0
1132
269
142
0
0
0
0
12
0
804
0
0
86
0
0
0
0
0
0
0
161
0
1796
0
0
0
0
0
0
0
0
0
0
0
0
113
0
0
0
0
0
0
0
0
0
799
0
0
270
0
150
0
0
0
0
0
0
463
0
0
0
0
0
0
0
0
0
0
0
0
1363
6
273
118
0
0
0
0
0
0
0
0
6463
0
0
0
691
330
0
5
0
0
0
229
0
231
0
0
0
0
0
0
0
0
189
0
3850
0
0
0
57
0
0
0
0
177
0
0
0
0
0
0
0
0
0
0
0
0
284
0
0
0
0
0
0
0
0
0
192
0
0
0
61
21
0
0
0
0
0
0
0
271
115
71
3
3173
0
48
192
0
161
0
0
0
0
126
0
0
0
0
0
0
136
0
0
0
0
360
0
0
2214
0
0
0
0
57
0
0
315
0
0
0
0
268
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
67
0
0
30
0
45
0
0
0
1120
0
3
0
0
4
0
16
0
0
0
0
0
0
111
0
0
2648
0
0
0
166
0
0
0
0
0
0
0
372
12
0
0
0
0
237
0
0
0
0
0
0
304
0
0
0
52
10
0
0
0
0
0
0
0
0
115
774
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
932
0
0
0
0
66
0
0
0
0
107
0
0
0
0
0
5760
0
0
0
0
0
0
0
0
0
0
0
0
9
0
0
20
230
216
0
0
0
0
0
0
0
0
0
0
0
148
0
0
0
0
55
0
0
0
0
0
0
0
293
0
0
8
0
0
275
0
0
343
0
154
0
367
0
75
0
0
193
0
0
1282
93
0
6
0
162
772
0
0
364
74
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
322
0
0
0
0
192
0
0
0
381
37
0
0
563
0
0
0
0
0
0
0
0
278
0
0
1899
0
0
0
0
183
402
0
138
0
0
0
0
0
0
0
0
0
0
0
0
13
0
231
598
0
216
0
0
0
0
7
0
0
0
0
0
0
47
0
0
0
0
0
0
400
0
0
33
0
0
0
0
0
0
0
0
0
11482
0
0
0
0
0
0
0
0
61
0
0
0
0
0
0
457
3039
0
0
0
327
0
0
0
0
0
0
0
0
0
0
432
0
0
0
0
0
0
0
0
198
15
0
0
0
232
68
0
0
0
0
161
0
0
1301
0
890
0
0
0
0
0
109
0
0
0
0
0
0
0
0
0
0
111
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
145
0
0
0
0
0
0
0
0
383
0
0
0
20
0
24
673
0
0
107
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2299
0
0
0
52
0
0
2244
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
18
0
0
0
1128
0
0
0
0
0
0
0
0
0
0
0
34
0
116
0
0
0
251
553
0
0
0

### Cleaning the Data

In [42]:
data = df.copy()

data = data.drop(columns = ["Reviews", "Metacritic url", "AppID", "Screenshots", "Movies", "Categories", "Notes", "Windows", "Linux", "Mac", "Discount", "DLC count", "About the game", "Supported languages", "Full audio languages", "Header image", "Website", "Support url", "Support email", "User score", "Positive", "Negative", "Score rank"])
data = data.drop(data[data['Average playtime forever'] <= 0].index)
print(data.count())
data.head()

Name                          27013
Release date                  27013
Estimated owners              27013
Peak CCU                      27013
Required age                  27013
Price                         27013
Metacritic score              27013
Achievements                  27013
Recommendations               27013
Average playtime forever      27013
Average playtime two weeks    27013
Median playtime forever       27013
Median playtime two weeks     27013
Developers                    27013
Publishers                    26779
Genres                        26943
Tags                          24866
dtype: int64

,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Metacritic score,Achievements,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Genres,Tags
1,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,0,0,231,8,0,8,0,minori,MangaGamer,Adventure,"Adventure,Visual Novel,Anime,Cute"
6,Armored Brigade II,"Apr 8, 2025",0 - 20000,8,0,35.99,0,0,107,675,0,1253,0,Veitikka Studios,Matrix Games,"Simulation,Strategy","Simulation,Strategy,RTS,Wargame,Grand Strategy..."
12,Fantasy General II,"Sep 5, 2019",100000 - 200000,13,0,13.99,80,77,994,489,0,52,0,Owned by Gravity,Slitherine Ltd.,Strategy,"Strategy,Turn-Based Strategy,Fantasy,Turn-Base..."
17,Redline,"Oct 23, 2014",0 - 20000,0,0,1.04,0,0,0,203,0,203,0,"Accolade, Inc.","Atari,Nightdive Studios","Action,Racing","Action,Racing,Gore,Violent,FPS,Classic,Post-ap..."
19,Fantasy Amusement Park,"Jul 28, 2023",0 - 20000,1,0,5.99,0,35,318,88,0,96,0,Cat Paw Game,Shark Shark Game,Casual,NaN