In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report

# pd.set_option("display.max_columns", None)

# # Show all rows
# pd.set_option("display.max_rows", None)

# # Increase maximum width per cell for long text
# pd.set_option("display.max_colwidth", None)

# # Increase the overall console display width to prevent wrapping
# pd.set_option("display.width", 1000)

### Exploring the Data

In [2]:
df = pd.read_csv("./games.csv")
df = df.sample(n=50000, random_state=42)
target = "Average playtime forever"
df.head(5)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
886,2839420,Topac Battle,"Jun 25, 2024",0 - 20000,1,0,3.99,0,1,"Welcome to Topac Battles , an idle game like n...",...,0,0,0,Keep Games,Keep Games,"Single-player,Steam Achievements,Family Sharing",Simulation,"Creature Collector,Idler,Clicker,Relaxing,Casu...",https://shared.akamai.steamstatic.com/store_it...,NaN
10521,2254890,The Killing Antidote,"Oct 5, 2024",100000 - 200000,343,0,23.99,20,0,"Synopsis In the future, a special germ will ca...",...,905,639,1354,MetalStar Studio,MetalStar Studio,"Single-player,Steam Achievements,Full controll...","Action,Adventure,Indie,RPG,Early Access","Early Access,Female Protagonist,Sexual Content...",https://shared.akamai.steamstatic.com/store_it...,NaN
64606,3108720,Silent: Abandoned,"Nov 2, 2024",0 - 20000,0,0,0.84,83,0,'Don't play with me!' 'Silent: Abandoned' is a...,...,0,0,0,Massbolt Games,Massbolt Games,"Single-player,Family Sharing","Indie,Simulation","Horror,Exploration,Walking Simulator,Psycholog...",https://shared.akamai.steamstatic.com/store_it...,NaN
86146,1449650,Casual Challenge Players Club- Anime Bilhar game,"Jan 25, 2021",0 - 20000,0,0,0.79,60,0,Casual Challenge is a classic arcade game for ...,...,0,0,0,Yume Game Studio,Yume Game Studio,"Single-player,Multi-player,PvP,Shared/Split Sc...","Casual,Indie,Sports,Strategy","Pool,Casual,Sports,Retro,Relaxing,Physics,Stor...",https://shared.akamai.steamstatic.com/store_it...,NaN
88254,2421690,Palladium,"Jul 31, 2023",20000 - 50000,0,0,9.99,0,0,Palladium is a one-man team videogame designed...,...,0,0,0,Must.iolo,Must.iolo,"Single-player,Family Sharing","Action,Indie,Early Access","Singleplayer,Old School,FPS,First-Person,Fast-...",https://shared.akamai.steamstatic.com/store_it...,NaN

In [3]:
print("Shape of the data:")
print(df.shape)
print()
print("Number of Missing Values in Each Column:")
print(df.isna().sum())
print()
print("Info About Each Column:")
print(df.info())
print()
print(df["Release date"].value_counts())

Shape of the data:
(50000, 40)

Number of Missing Values in Each Column:
AppID                             0
Name                              1
Release date                      0
Estimated owners                  0
Peak CCU                          0
Required age                      0
Price                             0
Discount                          0
DLC count                         0
About the game                 3403
Supported languages               0
Full audio languages              0
Reviews                       45199
Header image                     35
Website                       29954
Support url                   28140
Support email                  9082
Windows                           0
Mac                               0
Linux                             0
Metacritic score                  0
Metacritic url                48311
User score                        0
Positive                          0
Negative                          0
Score rank                    49983
Achievements                      0
Recommendations                   0
Notes                         40742
Average playtime forever          0
Average playtime two weeks        0
Median playtime forever           0
Median playtime two weeks         0
Developers                     3371
Publishers                     3586
Categories                     3594
Genres                         3375
Tags                          16848
Screenshots                    2376
Movies                        50000
dtype: int64

Info About Each Column:
<class 'pandas.DataFrame'>
Index: 50000 entries, 886 to 48711
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   AppID                       50000 non-null  int64
 1   Name                        49999 non-null  str
 2   Release date                50000 non-null  str
 3   Estimated owners            50000 non-null  str
 4   Peak CCU                    50000 non-null  int64
 5   Required age                50000 non-null  int64
 6   Price                       50000 non-null  float64
 7   Discount                    50000 non-null  int64
 8   DLC count                   50000 non-null  int64
 9   About the game              46597 non-null  str
 10  Supported languages         50000 non-null  str
 11  Full audio languages        50000 non-null  str
 12  Reviews                     4801 non-null   str
 13  Header image                49965 non-null  str
 14  Website                     20046 non-null  str
 15  Support url                 21860 non-null  str
 16  Support email               40918 non-null  str
 17  Windows                     50000 non-null  bool
 18  Mac                         50000 non-null  bool
 19  Linux                       50000 non-null  bool
 20  Metacritic score            50000 non-null  int64
 21  Metacritic url              1689 non-null   str
 22  User score                  50000 non-null  int64
 23  Positive                    50000 non-null  int64
 24  Negative                    50000 non-null  int64
 25  Score rank                  17 non-null     float64
 26  Achievements                50000 non-null  int64
 27  Recommendations             50000 non-null  int64
 28  Notes                       9258 non-null   str
 29  Average playtime forever    50000 non-null  int64
 30  Average playtime two weeks  50000 non-null  int64
 31  Median playtime forever     50000 non-null  int64
 32  Median playtime two weeks   50000 non-null  int64
 33  Developers                  46629 non-null  str
 34  Publishers                  46414 non-null  str
 35  Categories                  46406 non-null  str
 36  Genres                      46625 non-null  str
 37  Tags                        33152 non-null  str
 38  Screenshots                 47624 non-null  str
 39  Movies                      0 non-null      float64
dtypes: bool(3), float64(3), int64(15), str(19)
memory usage: 14.6 MB
None

Release date
Oct 23, 2025    76
Oct 24, 2025    72
Jul 31, 2025    68
Oct 31, 2025    63
Mar 6, 2025     62
                ..
Jun 1, 2011      1
Jan 24, 2007     1
Apr 24, 2016     1
Mar 29, 2011     1
Jan 1, 2018      1
Name: count, Length: 4544, dtype: int64

In [4]:
print(df[target].value_counts())

for item in df[target]:
    print(item)

Average playtime forever
0         39566
1           114
2            68
3            58
15           56
          ...
3629          1
1704          1
1815          1
2923          1
322983        1
Name: count, Length: 1900, dtype: int64
0
1092
0
0
0
386
0
0
0
0
0
406
740
0
0
0
11
0
0
159
1765
0
274
0
0
0
0
0
0
683
0
0
0
2068
0
0
0
0
812
0
0
0
0
133
0
0
0
1044
0
0
592
0
0
0
0
0
0
10
0
0
0
0
0
68
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1083
0
320
0
0
0
1249
0
0
0
35
0
2475
181
0
0
0
0
333
0
143
0
0
0
0
0
22
0
915
0
0
0
0
0
0
0
1014
0
0
0
0
0
201
129
327
0
134
685
0
0
0
0
37
0
0
118
211
0
665
2545
0
0
0
82
0
0
0
252
0
0
193
0
0
0
148
0
0
0
0
0
0
0
314
0
297
0
90
0
146
0
0
0
0
0
197
1255
0
0
0
0
435
0
0
0
38
0
33
261
0
0
0
0
0
263
0
171
0
1318
0
0
0
447
0
0
0
736
0
0
0
0
0
0
0
0
0
0
909
0
1260
0
0
485
0
238
0
608
0
0
58
2845
204
0
0
276
127
0
0
0
0
0
0
257
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
117
0
0
274
0
0
11
0
10
0
0
0
0
0
0
0
0
0
0
0
0
75
0
0
71
218
0
0
0
122
0
0
0
0
0
0
0
0
0
121
0
0
0
0
0
0
0
0
0
0
0
245
0
199
0
55
0
0
0
0
0
433
24
51
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
14
305
31
132
0
0
0
39
0
598
291
0
157
0
101
0
0
899
0
0
0
0
0
0
0
0
231
0
0
227
0
0
0
0
0
0
0
0
0
0
0
331
0
0
0
177
0
0
0
0
0
0
0
267
0
0
213
0
0
26
4749
0
612
0
2310
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
30
0
0
0
0
0
0
0
0
0
120
0
0
0
0
0
0
1187
0
304
279
0
0
400
0
0
0
393
0
0
0
0
324
0
85
0
0
0
0
0
0
0
0
0
0
0
0
246
0
0
0
0
0
204
0
0
0
439
0
0
237
0
0
0
0
0
0
0
0
19
0
0
1
0
0
0
541
0
0
0
0
0
0
0
0
231
0
0
0
0
0
343
0
0
0
123
42
0
0
0
0
0
287
180
0
0
176
234
0
0
0
0
55
0
0
0
0
0
1774
0
1236
0
0
0
0
0
0
76
0
255
34
0
190
0
352
56
313
1
0
0
15
0
169
0
0
0
186
0
0
0
0
0
0
0
0
0
479
0
0
2387
0
0
284
0
0
0
0
157
165
0
0
0
580
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
24
0
0
0
0
0
0
0
38
0
0
0
0
0
0
0
254
0
176
0
0
0
0
0
0
196
256
0
0
0
0
626
0
0
0
0
0
0
0
1000
0
499
286
6
0
72
8
0
0
684
0
647
86
86
0
0
0
0
0
0
0
0
0
846
0
3024
0
2
0
0
0
0
0
0
814
0
0
1046
2
0
0
119
0
481
1
0
0
0
0
0
0
0
0
0
0
0
0
155
0
0
0
580
0
0
0
0
0
0
0
0
92
0
0
0
545
0
0
0
157
0
0
0
0
0
0
0
36
70
0
0
0
85
0
0
0
0
0
0
0
0
0
0
0
0
0
0
792
0
0
170
185
0
0
0
160
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
245
353
0
0
0
0
0
0
0
237
0
188
1127
0
548
0
0
0
0
0
0
25
246
0
0
0
0
0
0
0
0
0
0
0
347
147
0
47
0
0
772
0
0
1390
0
0
0
0
0
0
0
0
0
0
0
0
0
412
254
0
65
0
0
0
0
0
0
0
0
0
149
0
0
0
0
0
0
0
0
0
0
0
0
0
0
38
0
0
0
0
0
0
0
0
0
0
271
1401
0
0
0
0
0
0
0
0
0
115
0
0
0
0
0
0
0
208
0
0
0
0
0
0
0
0
0
0
114
0
0
1652
0
0
0
0
0
350
0
0
0
0
0
0
0
0
0
147
0
0
0
0
0
0
0
0
0
0
381
0
0
0
0
0
0
0
0
15
0
125
0
0
0
0
0
0
0
0
0
0
85
0
0
327
0
0
0
0
0
227
0
0
686
0
0
0
0
0
0
0
11466
0
0
0
0
511
0
0
0
0
0
0
206
0
280
0
0
0
0
0
109
0
0
0
93
0
512
0
0
0
284
0
1856
0
0
193
0
0
0
0
0
194
233
0
0
0
0
0
0
0
0
17
0
0
0
32
0
0
0
0
152
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1358
0
0
4
0
0
0
0
0
0
0
0
0
0
0
0
0
96
0
0
0
0
233
0
0
0
0
0
260
0
0
0
0
0
0
0
0
0
0
12329
0
15
0
0
0
0
0
0
131
0
0
0
0
0
41
0
0
2988
0
0
0
0
2889
0
0
0
0
0
0
0
0
0
0
0
0
180
133
0
0
0
0
1011
0
0
2889
100
32
1237
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
113
0
0
0
0
0
0
0
0
0
0
0
746
0
0
2152
0
0
0
0
472
0
79
0
0
0
0
0
0
0
0
0
36
0
0
78
909
0
0
0
0
0
0
0
0
204
0
54
0
539
253
0
0
0
0
0
216
0
0
165
0
0
0
0
0
0
0
591
0
0
0
0
0
0
136
0
0
0
124
0
4
0
127
0
0
0
0
0
0
0
0
0
0
101
0
0
458
0
0
0
0
0
0
0
0
0
166
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1054
217
0
0
2691
0
0
0
0
0
0
0
0
0
0
474
0
0
229
0
0
0
115
0
0
0
54
0
0
0
0
0
0
0
0
0
0
25
0
0
0
226
0
0
496
0
0
0
0
0
0
0
290
0
0
0
0
0
0
0
0
143
0
0
0
0
0
0
0
0
11
0
0
0
0
0
0
0
0
0
89
0
0
0
0
90
0
0
0
0
0
162
0
611
0
0
0
0
0
145
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
18
30
0
0
0
789
0
0
403
246
0
0
0
0
0
0
26
0
0
0
0
0
0
0
0
0
526
0
0
0
0
0
0
0
0
176
0
0
0
0
10
0
0
15
0
0
0
0
869
192
0
80
0
0
1435
0
0
0
0
0
0
0
0
0
0
0
0
478
0
20
0
0
0
0
0
0
0
116
0
0
0
0
0
0
0
448
1293
0
0
0
0
0
46
0
576
0
0
0
0
120
263
0
0
64
14
0
0
0
0
0
758
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
82
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
484
0
0
1205
0
173
0
0
0
0
0
0
0
0
0
0
2136
620
0
0
0
0
0
0
0
0
0
0
0
413
0
22
0
0
0
0
0
0
0
0
0
0
0
347
0
0
0
0
0
0
0
0
0
0
0
0
0
225
0
0
0
0
0
18
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3079
0
0
0
317
0
0
0
0
0
122
0
0
0
0
0
0
0
0
258
0
4152
391
0
0
0
0
0
0
0
0
117
148
0
0
0
0
0
208
89
0
0
68
0
6
0
0
0
0
0
10
0
0
0
428
11
0
698
0
0
616
0
0
0
0
0
0
0
41
1315
0
0
1585
0
199
393
0
0
2497
0
0
143
0
744
0
0
5926
0
0
329
0
0
0
0
0
0
0
0
0
214
0
200
251
0
0
0
0
378
0
0
0
0
0
0
0
0
0
0
0
0
0
2455
0
171
0
0
0
105
0
0
0
0
0
0
895
0
0
0
0
0
0
0
0
0
0
459
0
0
0
124
122
0
0
0
0
0
0
0
0
0
717
0
0
201
0
0
246
0
0
356
0
0
0
86
412
0
0
0
0
0
0
0
0
91
0
575
0
284
0
0
0
0
1392
911
0
4
0
231
0
0
0
0
102
1352
381
0
0
0
1151
141
167
0
0
87
0
1
0
0
0
1212
333
0
0
548
0
0
0
0
0
0
0
0
0
0
0
0
0
0
405
0
0
0
0
0
0
0
235
0
0
391
0
0
0
0
199
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
187
0
0
0
0
0
125
0
0
0
0
0
8424
0
0
0
0
0
0
0
0
0
0
12
0
0
0
274
0
0
411
99
0
0
0
0
0
0
0
0
0
0
0
0
0
177
6603
0
0
0
0
195
0
0
0
0
0
0
0
0
0
631
0
0
0
0
0
0
0
0
0
0
1348
0
0
0
0
599
0
0
0
0
0
0
0
67
83
228
0
0
0
530
0
0
0
377
0
657
0
2
0
0
0
0
0
860
0
0
598
0
0
10
0
0
0
0
0
0
0
0
0
0
0
0
0
637
0
0
0
0
0
0
64
0
0
179
0
0
0
0
0
0
0
955
0
0
0
0
0
0
0
0
0
238
315
0
0
0
0
0
0
204
0
0
106
0
0
0
0
0
0
0
50
0
0
0
0
0
9
344
131
235
334
123
0
0
0
0
0
58
0
0
0
0
0
0
240
0
0
0
372
0
0
220
194
0
673
0
9
0
0
0
0
269
0
0
0
0
0
0
0
0
0
0
0
0
151
0
240
0
0
0
0
0
0
0
0
0
0
11
0
181
0
0
0
0
0
0
0
276
0
156
154
0
0
0
0
0
0
5942
0
0
0
0
0
0
0
0
75
0
0
0
0
0
0
0
0
0
0
0
1411
0
425
135
0
0
94
0
0
0
0
0
0
0
0
147
0
0
0
0
0
0
0
0
1889
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1060
0
0
385
0
0
25
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
89
201
112
345
0
74
0
0
0
0
21
0
0
0
0
0
0
842
0
16
0
0
47
0
0
0
0
0
0
0
1521
0
0
0
0
0
0
0
341
0
0
444
57
471
0
0
0
0
0
0
0
0
0
0
94
0
0
0
0
0
0
198
0
0
0
3908
0
0
0
0
207
0
0
0
19
423
158
0
0
244
26
0
18
0
0
0
0
0
0
0
0
0
0
0
0
35
0
0
251
0
0
43
334
0
0
0
0
0
0
0
640
0
517
669
348
0
0
24
0
0
316
95
0
0
0
0
0
0
0
0
0
13
0
0
0
0
0
0
86
0
0
100
0
0
0
0
0
0
0
0
0
197
209
0
0
0
0
0
0
0
0
17
0
0
0
0
0
0
0
0
0
17
0
0
0
0
666
0
0
0
0
0
0
0
0
0
0
0
0
0
305
0
0
0
0
11
0
0
0
0
189
580
16
0
0
0
43
0
406
0
0
0
0
0
0
0
0
0
0
0
0
0
8
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
203
377
39
0
0
0
0
0
0
226
0
0
0
0
815
0
0
0
0
0
909
0
0
0
0
0
209
1573
0
1178
0
0
0
0
0
0
0
0
0
1061
81
0
484
0
0
0
0
0
0
0
0
0
287
0
0
0
0
0
0
0
0
0
1104
90
0
316
0
0
0
176
0
0
0
0
0
0
0
0
43
0
0
0
0
0
0
21
0
0
0
0
0
0
0
0
0
203
0
0
0
0
0
0
0
0
0
0
1196
0
0
0
0
0
0
0
0
0
0
0
0
0
529
1884
0
0
192
13
62
0
1
213
0
16
0
142
0
0
0
68
0
0
9
0
0
0
30
4883
415
0
0
0
0
0
0
0
0
0
552
0
0
0
0
0
310
0
68
0
0
0
256
0
0
86
0
0
15330
0
0
0
0
0
0
0
1112
217
0
0
0
0
280
0
0
0
0
0
0
0
0
0
0
0
0
360
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
24
0
0
0
668
0
0
0
92
0
153
57
1679
16
216
0
0
0
0
0
11
0
0
0
149
0
0
0
0
18
0
0
0
0
0
733
327
0
571
0
0
0
101
0
0
0
0
0
0
0
250
0
0
0
0
0
0
1359
0
0
0
0
0
0
0
602
0
0
0
0
0
0
0
38
0
0
0
0
319
0
0
0
0
0
0
0
0
0
0
0
464
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
4
0
426
95
24
0
838
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
61
0
0
22
0
0
59
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1349
0
251
0
0
511
0
0
0
0
0
0
1636
0
0
0
496
0
186
0
0
363
0
0
0
0
0
0
0
0
0
3502
0
63
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
50
0
0
775
0
0
0
0
0
434
0
0
82
397
0
0
0
0
0
8
0
0
0
0
0
1027
0
0
1446
0
0
0
0
233
0
169
0
528
0
1843
1957
0
0
0
0
0
0
0
168
0
0
62
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1425
0
0
0
0
56
0
252
0
0
0
235
0
0
0
777
0
289
0
0
0
0
0
0
0
0
0
0
122
21
537
0
0
0
0
0
0
1147
0
0
0
0
0
0
343
0
60
0
0
129
0
2259
16
0
0
0
0
0
731
0
0
0
0
0
173
10
0
151
0
0
0
0
0
0
0
0
94
0
0
0
0
7
358
428
0
0
0
0
0
0
0
0
0
0
0
0
0
157
0
0
1086
0
0
162
0
86
0
0
31
0
0
1
0
0
0
0
57
0
0
0
0
0
307
0
303
0
0
167
0
0
266
0
574
22
0
0
0
0
0
0
0
0
0
530
3
0
0
0
0
0
79
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
402
0
0
27
0
0
0
0
0
0
0
0
0
67
0
0
0
0
0
0
0
561
0
0
0
0
0
7
27
0
0
0
0
0
142
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
24
0
0
1722
0
0
0
0
0
0
0
22837
0
0
0
0
183
1223
398
202
0
0
316
0
0
0
0
0
0
0
0
0
0
0
232
0
0
0
0
0
0
0
0
1075
0
0
0
0
0
0
8
16
0
0
0
0
115
0
0
219
0
0
0
0
0
0
275
0
72
0
0
0
0
0
0
0
0
0
0
290
0
104
0
0
0
0
0
0
0
0
0
0
152
0
0
46
94
0
2174
0
0
0
22
0
0
0
0
0
0
73
0
426
0
0
50
0
0
0
0
0
0
0
580
0
0
0
396
0
0
67
0
0
0
253
0
0
0
0
0
0
269
528
0
200
24
33
0
2
843
28565
0
0
0
0
0
0
0
222
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
48
0
989
0
659
0
0
0
0
0
205
0
0
0
87
468
0
0
0
0
0
0
0
0
0
0
227
0
272
0
194
0
0
0
0
0
0
0
0
0
0
0
0
121
0
0
0
0
0
0
0
0
0
0
0
0
0
297
0
0
0
0
0
0
0
371
0
0
42
0
0
0
0
0
0
0
601
0
0
0
0
0
0
231
0
0
0
180
0
0
0
0
0
0
0
0
0
0
1569
0
0
312
0
0
31
0
0
0
0
114
0
0
0
15992
0
0
0
0
0
2171
387
0
0
0
0
0
0
0
0
0
1356
0
663
0
183
2659
0
0
0
0
1
356
2526
0
0
0
0
0
0
0
0
107
0
0
0
0
0
176
0
23
0
0
0
1031
0
0
0
261
1166
0
0
0
37
0
0
0
0
80
0
0
0
0
0
0
0
0
0
19
0
0
176
0
0
0
0
0
0
0
221
0
0
0
0
0
0
1
0
0
0
0
0
161
0
0
0
554
0
0
0
0
0
406
42
0
0
0
804
0
0
0
0
0
0
0
0
169
174
34
0
0
0
0
0
0
299
0
0
0
0
20
0
0
229
0
0
1053
0
77
0
927
0
0
0
0
0
0
0
0
31
0
0
0
57
488
485
0
0
262
0
0
0
0
0
210
11
0
0
0
0
2353
0
0
12
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
239
0
0
34
65
0
48
46
0
8
0
0
15
0
0
0
0
1746
0
134
0
0
0
0
0
0
0
83
0
0
63
283
0
0
0
0
0
0
182
0
902
0
0
0
0
0
0
63
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
432
215
0
0
0
50
0
0
0
152
0
0
0
0
0
0
0
30
292
0
215
484
0
0
1145
0
0
0
494
0
106
0
0
887
0
0
0
0
0
0
0
0
0
0
303
0
0
0
0
313
0
0
0
239
0
0
0
0
0
0
0
244
0
54
0
0
0
0
0
203
0
0
0
366
0
0
0
0
0
61
0
0
0
831
0
0
325
0
0
0
30
0
0
3093
0
0
0
0
0
0
0
0
0
0
0
0
0
713
476
0
0
0
0
0
0
0
0
0
1010
0
0
0
0
0
0
0
0
0
0
277
0
0
0
0
643
0
0
0
0
142
0
0
0
0
0
93
0
0
0
0
0
0
0
401
0
0
0
153
40
784
490
137
0
0
0
0
739
0
230
0
41
0
0
0
0
0
0
0
0
111
0
0
3023
0
0
122
0
0
203
0
0
0
10
0
0
0
126
0
31
0
0
0
0
0
0
0
0
0
0
10
0
0
0
0
0
54
0
0
0
112
49
0
0
36
0
487
103
0
0
33
32
402
0
0
0
0
0
0
0
0
0
0
0
378
0
0
2530
43
8
0
0
0
0
0
0
0
0
467
0
0
1032
0
0
7
0
250
0
363
0
0
0
0
0
0
55
0
0
0
0
0
0
0
466
50
0
0
0
22
5
0
0
1033
0
0
0
0
0
0
142
0
116
1668
0
0
0
0
0
457
0
0
0
0
0
0
0
0
0
0
277
0
0
377
0
0
119
0
0
0
0
0
0
0
0
0
0
0
0
680
344
419
0
0
411
0
0
0
6425
0
0
0
0
0
0
0
0
0
2751
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
118
109
0
0
0
0
0
0
0
0
0
2552
0
0
0
0
0
0
0
0
265
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
131
0
0
0
0
215
333
0
0
0
15
0
192
1114
0
0
0
0
0
0
0
22
0
36
0
0
0
0
0
3
0
294
0
0
0
0
0
0
0
0
0
0
0
89
0
0
0
0
124
0
0
0
0
394
0
207
0
8
0
0
0
3106
0
390
0
0
264
0
707
987
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
20
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
290
0
0
0
1
0
0
0
0
0
0
885
333
0
0
0
0
0
0
0
1939
0
0
321
0
0
0
0
0
1035
0
0
0
0
0
0
5
0
0
540
0
0
0
0
0
0
0
300
0
0
0
0
0
0
0
0
0
0
0
28
214
0
125
0
0
0
0
0
0
0
0
0
0
1434
0
0
0
0
2188
0
0
0
20
0
17
0
0
0
0
17
0
53
0
359
0
0
0
0
0
259
0
0
101
148
0
0
0
0
8
0
0
0
0
380
0
0
0
0
0
0
339
0
0
0
1250
204
0
0
0
0
0
192
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
912
0
0
245
0
0
37
0
0
0
0
0
0
0
0
0
0
0
0
0
123
169
0
0
0
0
76
0
0
0
0
0
0
0
0
0
0
213
0
0
0
0
0
0
0
150
0
0
0
0
37
0
206
0
1030
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
604
0
0
38
58
338
0
451
0
0
931
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
560
0
0
30
0
0
3580
0
0
0
0
0
0
344
457
0
381
197
0
0
0
0
0
0
0
0
0
156
0
0
364
0
0
10
91
37
18
199
0
0
0
4
0
99
0
91
0
0
0
0
0
0
0
0
0
0
253
0
0
0
0
0
0
0
223
16
0
350
0
0
0
0
0
0
0
0
0
0
489
60
0
0
461
0
0
0
0
0
0
78
0
0
0
0
0
0
0
3882
0
0
0
0
0
0
0
216
0
0
0
0
0
0
0
0
0
0
354
0
0
0
0
406
0
0
0
0
1357
0
0
62
0
0
24
84
0
0
0
0
0
290
51
0
0
0
0
2407
0
0
0
86
0
0
307
4766
667
0
0
0
106
0
0
120
576
0
167
184
0
0
0
0
0
0
0
0
0
0
0
0
289
0
0
0
0
0
0
0
0
0
0
0
0
0
386
0
0
0
0
0
304
0
539
0
0
0
0
0
0
226
17
87
294
0
148
0
0
0
0
1
0
603
0
0
0
0
16
0
206
0
0
0
0
0
0
52
0
0
0
473
0
0
3
0
0
10
0
150
0
0
15020
191
0
0
245
0
0
406
0
0
0
0
400
513
0
155
0
0
0
642
127
0
0
0
423
0
0
445
0
0
0
0
0
0
0
95
0
871
0
3807
0
0
274
73
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
34
0
0
34
0
0
223
0
638
1208
0
0
0
0
0
0
0
0
185
0
966
0
0
0
1345
0
0
0
409
0
326
0
0
253
0
0
16
142
2572
0
0
19
0
0
0
0
0
0
658
0
40
234
0
0
0
0
0
0
0
0
0
243
0
0
649
0
0
956
0
0
160
0
2269
0
0
95
1072
0
102
0
0
27
0
53
0
0
0
337
0
123
0
0
0
0
970
829
6205
2
0
383
0
0
0
0
196
0
0
0
336
0
131
0
0
0
0
0
83
0
0
0
0
0
0
0
0
469
0
381
0
0
79
0
0
0
0
158
0
0
0
0
0
0
0
0
4294
0
0
0
0
0
0
0
20
753
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
35
0
0
264
0
0
0
267
0
0
0
0
0
0
1245
0
63
0
0
0
0
0
0
0
0
0
0
404
1119
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
76
0
0
0
0
0
166
0
0
0
0
0
0
0
0
0
154
0
0
0
0
0
0
0
0
0
0
0
0
0
0
51
0
93
5326
6
0
0
0
0
0
0
418
0
0
0
0
0
1005
97
237
0
0
0
146
1412
0
0
0
528
0
0
145
0
0
2377
0
0
0
0
51
79
0
166
0
0
0
0
689
0
0
0
0
0
0
0
0
0
504
0
23
0
14
72
0
0
0
191
0
0
0
0
0
0
0
0
0
1191
0
278
0
1142
0
0
0
4701
0
0
0
127
392
0
0
0
0
0
0
73
128
0
0
0
0
0
0
0
0
0
0
0
0
0
55
0
0
89
0
0
0
0
0
0
1320
0
0
0
357
0
0
350
0
0
0
0
0
0
0
0
0
0
0
0
0
0
71
0
0
0
0
0
0
0
0
0
636
0
0
0
0
0
0
0
0
611
0
0
0
207
0
0
69
0
0
0
0
0
1063
0
47
0
0
243
0
308
0
0
0
0
0
0
4153
0
0
0
0
0
0
0
148
0
0
0
0
0
43
0
0
0
0
0
0
152
0
0
0
0
0
0
67
0
0
7
0
0
0
0
0
0
6
0
0
0
0
0
0
1
0
0
0
0
341
0
0
0
0
0
0
0
61
0
0
0
0
512
0
0
313
0
0
0
0
473
0
175
0
23
0
0
42
0
0
0
0
0
0
0
0
0
0
6
0
195
0
0
0
0
358
0
0
0
213
0
0
0
0
0
0
0
1017
0
0
0
0
0
0
0
0
613
11
363
0
0
0
0
1
1
349
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
89
182
16
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1011
3
0
0
0
0
0
0
0
2
0
0
0
966
0
0
0
6
0
41
0
0
0
318
0
0
0
623
0
0
0
0
0
0
0
0
0
0
0
0
495
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
171
18
108
0
0
0
0
96
0
0
0
0
0
0
0
0
0
0
0
84
252
148
0
0
0
0
0
108
0
0
137
0
0
0
0
0
3017
0
0
18
0
0
377
0
0
0
0
0
0
100
4876
0
209
358
0
0
185058
0
0
0
148
366
0
0
0
507
1
0
0
280
0
0
0
0
0
0
0
0
0
0
0
0
881
0
0
0
0
0
0
0
0
0
0
220
0
0
0
0
0
0
16
0
0
0
0
0
0
28
0
0
0
0
0
0
0
0
0
0
163
0
0
0
8786
0
0
0
0
0
0
0
0
0
230
166
372
2347
0
0
0
0
0
78
0
189
0
0
0
0
0
0
0
0
0
0
0
0
1580
40
0
157
0
219
0
0
0
0
0
0
0
0
0
0
0
0
0
213
0
0
38
0
0
0
635
0
0
0
212
0
88
0
0
205
0
0
0
0
0
0
0
0
292
0
0
0
0
219
0
0
0
0
0
0
0
0
192
0
0
0
0
48
0
0
0
0
0
0
0
0
0
51
237
0
0
28
0
0
0
0
0
0
0
0
0
0
0
459
272
0
0
0
0
0
0
0
0
0
202
0
0
0
0
0
0
150
0
0
0
23837
0
148
0
0
0
14
0
0
0
0
0
0
0
0
86
0
0
0
0
0
0
44
0
0
0
0
0
0
0
245
0
0
0
0
49
0
133
0
0
8887
10328
0
419
0
0
0
0
62
91
497
0
0
0
0
0
0
85
0
0
0
0
0
0
0
0
69
0
81
0
0
0
0
0
0
0
0
0
0
0
0
245
0
0
0
0
0
0
0
25
0
0
0
0
0
0
0
0
160
0
0
0
211
0
0
0
229
0
0
1355
0
0
0
0
0
0
276
0
0
214
0
0
0
132
676
0
278
0
0
0
232
0
0
0
0
84
230
1134
0
0
0
0
0
0
133
0
0
0
0
203
0
0
0
112
27
0
0
0
23
0
0
1
0
0
0
0
0
0
0
0
0
0
331
0
0
0
0
116
0
0
25
0
0
0
0
188
0
0
1537
801
217
0
942
312
263
0
0
0
0
0
0
0
0
0
0
0
76
108
0
128
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
382
0
0
0
0
0
0
205
420
0
0
58
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
11
0
0
0
0
0
288
386
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
90
0
0
0
0
0
0
0
0
0
0
0
0
728
36
0
11
0
0
0
0
0
0
0
0
0
0
0
0
0
0
75
0
0
714
9
0
481
0
0
464
0
0
0
0
913
0
0
0
0
168
0
0
0
56
263
1522
0
0
0
0
0
0
0
147
0
83
0
0
0
0
0
0
0
0
0
0
0
0
0
0
372
241
0
0
0
137
0
0
0
0
0
0
0
0
0
111
0
547
0
214
0
0
0
271
0
265
0
0
0
133
0
159
0
0
0
0
121
0
0
0
0
265
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
108
0
114
0
142
0
301
0
0
0
0
61
0
215
0
0
0
0
697
0
0
0
0
0
0
0
147
0
0
205
0
0
0
605
0
0
0
0
0
0
0
0
0
0
0
0
0
0
13
0
0
0
0
0
0
0
0
0
0
449
0
0
26
28
0
0
0
66
0
0
0
0
0
129
3455
0
151
0
0
101
0
263
0
0
2164
0
202
0
13
123
0
0
0
714
241
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
160
0
0
0
0
0
0
0
512
173
0
0
0
275
216
0
0
0
0
0
154
0
0
242
0
0
1557
1540
53
0
0
0
0
8631
0
191
144
0
0
0
204
0
0
0
360
204
0
0
0
0
0
695
0
0
0
0
0
0
0
0
240
0
0
166
0
0
0
205
0
0
0
0
0
35
0
0
8
32
0
6
280
339
0
0
43
0
0
0
0
0
0
0
729
0
0
0
0
0
0
0
422
0
0
0
195
0
0
0
0
0
0
255
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
98
0
0
0
0
0
0
0
0
0
624
0
122
0
0
0
0
0
0
78
47
0
0
0
1066
0
246
0
0
0
0
0
0
0
313
0
0
0
0
0
0
115
718
205
0
0
0
0
0
0
0
0
56
267
0
0
0
0
69
0
0
0
0
0
0
0
402
760
0
260
0
0
0
0
0
0
0
903
0
0
73
0
0
0
309
0
0
0
469
0
0
0
0
0
0
34
0
0
0
530
0
247
0
0
1107
0
0
0
0
0
0
0
0
231
0
123
0
0
0
0
0
0
147
0
98
0
0
0
0
107
0
105
2172
0
0
0
0
3
0
0
0
0
636
0
0
40
58
291
144
0
0
0
0
0
0
0
0
0
0
0
0
0
278
0
286
0
0
0
0
0
0
0
0
0
0
290
0
0
0
0
78
50
0
0
0
0
164
314
0
0
0
0
261
0
0
0
0
0
8291
0
0
0
0
111
0
0
0
561
0
0
0
0
0
465
0
0
743
0
0
0
0
0
0
0
574
0
0
0
0
0
0
353
0
0
0
0
0
0
0
0
0
17
0
0
0
1295
16014
0
0
0
0
0
0
0
0
0
1728
0
0
0
0
0
756
0
0
278
272
0
0
0
0
0
0
0
0
0
255
0
0
0
0
0
0
0
663
0
0
140
0
0
0
0
883
0
0
0
0
0
0
0
121
0
0
0
381
0
267
0
0
0
0
0
0
0
0
0
0
2158
0
0
2242
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
576
869
0
164
548
0
0
0
0
0
0
0
0
0
0
0
0
0
14
0
0
0
0
0
0
189
0
0
0
0
0
0
0
0
822
0
0
216
0
0
85
0
0
0
0
0
0
0
0
0
0
232
729
0
0
0
0
0
0
0
0
0
0
0
128
477
0
0
0
0
0
212
0
0
143
0
0
0
0
15
0
382
0
0
0
0
0
0
0
0
0
0
0
0
0
105
0
0
0
0
0
150
133
0
0
0
0
0
0
0
144
0
0
0
0
0
0
0
0
0
0
0
583
0
0
1973
0
156
0
0
0
0
0
1851
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
198
0
0
525
0
0
0
0
0
0
0
445
5420
0
0
0
562
0
0
0
0
0
0
0
3952
0
0
0
0
551
0
0
0
0
0
51
1368
0
0
0
0
5771
0
0
0
0
163
0
0
0
0
0
0
0
0
355
0
0
0
161
0
0
0
0
256
0
1665
0
0
0
0
0
0
0
0
0
0
156
0
0
259
0
117
0
0
0
62
0
0
0
0
0
0
0
0
0
0
0
0
0
274
0
0
0
0
0
56
43
0
0
0
0
291
0
0
0
0
0
298
0
0
0
0
190
0
0
0
0
0
0
82
0
0
0
0
0
0
0
0
0
230
0
0
0
33
162
0
0
354
218
0
0
80
0
0
0
0
0
0
0
199
112
28
0
0
5388
0
0
375
0
251
0
611
0
0
138
0
0
0
0
0
0
0
0
0
777
0
0
0
0
0
0
0
886
54
0
0
0
0
0
0
146
235
0
209
22
0
0
0
0
0
78
0
0
0
0
0
193
0
212
279
0
0
0
2294
0
0
746
341
367
0
0
0
165
0
0
0
0
0
0
0
0
0
0
0
0
0
0
29
0
0
107
0
0
0
0
0
0
30
0
0
312
532
0
0
0
0
0
0
333
0
0
36148
0
1483
0
0
151
0
254
0
0
0
0
0
0
0
0
0
98
174
0
12
0
0
0
0
0
0
0
0
1692
0
0
0
0
168
0
367
0
0
0
370
0
0
0
0
248
76
0
0
843
0
0
0
104
0
0
0
0
0
0
0
0
0
0
0
0
0
144
0
0
0
0
0
0
0
0
0
0
0
0
0
2308
260
0
0
0
1703
0
0
3
0
3
0
0
0
0
435
0
0
0
0
0
0
0
2244
36
0
0
0
0
21
0
0
0
0
0
0
0
0
0
0
0
0
0
253
0
44
4
0
0
0
0
0
0
0
0
0
0
0
50
0
0
0
0
0
0
87
0
128
0
0
465
0
0
1518
0
0
105
0
0
279
0
0
1
0
0
0
0
0
0
0
183
0
0
260
898
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
71
0
67
0
0
270
0
58
92
0
0
141
0
199
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
28
0
67
0
121
0
0
0
0
0
0
0
0
0
0
0
0
0
188
0
0
0
0
0
0
0
11
0
0
0
0
45
0
0
94
0
0
0
0
0
1108
21
0
0
0
0
43
0
0
0
42
0
152
0
0
0
0
0
0
0
158
1
0
0
0
0
0
156
0
101
0
529
0
0
0
0
0
1
0
452
0
0
0
40
0
0
0
0
1938
0
0
0
0
290
0
0
0
552
0
0
0
0
119
0
0
158
0
0
566
0
0
9321
181
0
0
0
0
13
0
0
0
261
118
0
626
0
0
252
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
130
0
0
0
108
0
0
0
8
0
0
393
0
443
0
196
0
0
0
0
0
0
0
0
0
0
0
0
276
0
0
0
0
159
233
0
0
0
0
0
1682
83
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1029
0
0
0
0
0
344
0
0
0
0
0
134
0
0
0
0
290
0
0
0
0
0
48
0
0
48
0
0
0
0
0
1962
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
309
0
0
0
129
262
0
791
0
0
274
0
0
0
0
0
0
0
0
0
0
0
222
0
1586
0
0
0
0
894
0
0
0
170
0
131
863
0
164
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
325
516
299
0
0
0
0
0
0
0
0
0
0
0
77
0
286
0
0
0
0
127
0
0
0
652
0
0
194
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
149
459
0
0
0
0
0
0
0
0
0
5216
0
0
0
0
0
0
1188
0
0
0
0
0
0
0
249
205
37
1061
0
0
0
387
0
510
0
0
0
2
0
0
0
183
0
0
0
0
23
0
0
0
0
0
0
4
0
0
0
263
0
0
0
0
0
0
0
0
0
0
0
396
0
103
0
0
0
0
0
0
0
0
0
0
0
0
0
411
0
209
0
247
0
0
0
81
0
0
0
0
309
0
0
0
0
232
0
765
0
0
0
0
0
0
165
148
0
0
0
0
0
252
0
1
0
0
0
0
212
14
0
0
0
91
0
646
0
622
25
612
0
0
0
34
0
0
0
0
0
0
351
0
0
0
0
0
2400
0
0
32
0
985
0
61
0
0
0
0
0
0
0
224
0
0
0
143
0
333
0
0
288
0
0
0
0
0
0
0
0
394
0
0
0
0
0
0
0
0
0
0
0
128
0
0
0
0
0
0
15
0
0
0
0
0
0
171
0
0
0
35
0
0
151
0
0
0
0
0
602
724
0
0
274
0
0
0
0
0
0
0
2013
0
0
0
0
0
0
0
328
264
0
0
0
389
0
0
0
0
0
0
0
32
0
0
1133
0
0
0
198
0
0
0
0
0
0
4699
216
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
299
0
0
0
0
0
0
201
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
695
0
0
0
0
61
887
0
0
0
0
178
0
0
245
0
0
0
0
0
0
92
0
278
969
107
0
0
0
0
0
424
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1932
373
0
0
0
97
0
0
0
357
0
216
0
0
256
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
312
33
747
0
116
0
60
605
0
942
0
0
0
0
0
0
1071
0
0
0
0
266
0
0
0
0
0
244
287
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
352
0
32
0
0
0
0
361
112
0
0
552

### Cleaning the Data

In [10]:
data = df.copy()

data = data.drop(columns = ["Screenshots", "Movies", "Categories", "Notes", "Windows", "Linux", "Mac", "Discount", "DLC count", "About the game", "Supported languages", "Full audio languages", "Header image", "Website", "Support url", "Support email", "User score", "Positive", "Negative", "Score rank"])
data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Reviews,Metacritic score,Metacritic url,Achievements,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Genres,Tags
886,2839420,Topac Battle,"Jun 25, 2024",0 - 20000,1,0,3.99,NaN,0,NaN,18,0,0,0,0,0,Keep Games,Keep Games,Simulation,"Creature Collector,Idler,Clicker,Relaxing,Casu..."
10521,2254890,The Killing Antidote,"Oct 5, 2024",100000 - 200000,343,0,23.99,NaN,0,NaN,18,6177,1092,905,639,1354,MetalStar Studio,MetalStar Studio,"Action,Adventure,Indie,RPG,Early Access","Early Access,Female Protagonist,Sexual Content..."
64606,3108720,Silent: Abandoned,"Nov 2, 2024",0 - 20000,0,0,0.84,NaN,0,NaN,0,0,0,0,0,0,Massbolt Games,Massbolt Games,"Indie,Simulation","Horror,Exploration,Walking Simulator,Psycholog..."
86146,1449650,Casual Challenge Players Club- Anime Bilhar game,"Jan 25, 2021",0 - 20000,0,0,0.79,NaN,0,NaN,7,0,0,0,0,0,Yume Game Studio,Yume Game Studio,"Casual,Indie,Sports,Strategy","Pool,Casual,Sports,Retro,Relaxing,Physics,Stor..."
88254,2421690,Palladium,"Jul 31, 2023",20000 - 50000,0,0,9.99,NaN,0,NaN,0,0,0,0,0,0,Must.iolo,Must.iolo,"Action,Indie,Early Access","Singleplayer,Old School,FPS,First-Person,Fast-..."